# Generated by Django 5.2.1 on 2026-06-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0008_izinstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemkegiatan',
            name='status',
            field=models.CharField(choices=[('terjadwal', 'Terjadwal'), ('on_progress', 'On Progress'), ('menunggu_approval', 'Menunggu Approval'), ('selesai', 'Selesai')], default='terjadwal', max_length=20),
        ),
    ]
