# Generated by Django 5.2.1 on 2026-06-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0009_alter_itemkegiatan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankegiatan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
