# Generated by Django 5.2.1 on 2026-06-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0010_laporankegiatan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkegiatan',
            name='keterangan_overtime',
            field=models.TextField(blank=True, help_text='Wajib diisi jika keterlambatan lebih dari 1 jam.'),
        ),
        migrations.AddField(
            model_name='itemkegiatan',
            name='waktu_selesai_aktual',
            field=models.DateTimeField(blank=True, help_text='Waktu aktual saat staff mengupload foto after (otomatis diisi sistem).', null=True),
        ),
        migrations.CreateModel(
            name='FotoItemKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto_item/tambahan/')),
                ('jenis', models.CharField(choices=[('tambahan', 'Foto Tambahan'), ('kondisi', 'Kondisi Lapangan'), ('kendala', 'Kendala / Hambatan'), ('lainnya', 'Lainnya')], default='tambahan', max_length=20)),
                ('keterangan', models.CharField(blank=True, help_text='Keterangan singkat konteks foto (opsional).', max_length=300)),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_tambahan', to='outsourcing.itemkegiatan')),
            ],
            options={
                'verbose_name': 'Foto Tambahan Item Kegiatan',
                'verbose_name_plural': 'Foto Tambahan Item Kegiatan',
                'ordering': ['urutan', 'diunggah_pada'],
                'indexes': [models.Index(fields=['item', 'urutan'], name='idx_foto_item_urutan')],
            },
        ),
    ]
