# Generated by Django 5.2.1 on 2026-06-09 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0011_itemkegiatan_keterangan_overtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LokasiAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meter', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='lokasi_absensi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lokasi Absensi',
                'verbose_name_plural': 'Lokasi Absensi',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='qrabsensi',
            name='lokasi',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika absensi tidak perlu validasi lokasi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='outsourcing.lokasiabsensi'),
        ),
    ]
