# Generated by Django 5.2.1 on 2026-06-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0012_lokasiabsensi_qrabsensi_lokasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='standar',
            field=models.CharField(blank=True, help_text='Standar kualitas untuk task ini.', max_length=200),
        ),
    ]
