# Generated by Django 5.2.1 on 2026-06-12 02:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0013_task_standar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasiabsensi',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lokasiabsensi',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lokasiabsensi',
            name='radius_meter',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='lokasiabsensi',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='lokasi_yang_dibuat', to=settings.AUTH_USER_MODEL),
        ),
    ]
