# Generated by Django 5.2.1 on 2026-06-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0014_alter_lokasiabsensi_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporankegiatan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('selesai', 'Selesai')], default='draft', max_length=20),
        ),
    ]
