# Generated by Django 6.0.6 on 2026-06-23 04:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0015_alter_laporankegiatan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrabsensi',
            options={'ordering': ['supervisor', 'tipe'], 'verbose_name': 'QR Absensi'},
        ),
        migrations.AlterUniqueTogether(
            name='qrabsensi',
            unique_together={('supervisor', 'tipe')},
        ),
        migrations.AddField(
            model_name='qrabsensi',
            name='diperbarui',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lokasiabsensi',
            name='radius_meter',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.RemoveField(
            model_name='qrabsensi',
            name='berlaku_hingga',
        ),
        migrations.RemoveField(
            model_name='qrabsensi',
            name='jam_berlaku_mulai',
        ),
        migrations.RemoveField(
            model_name='qrabsensi',
            name='tanggal',
        ),
        migrations.CreateModel(
            name='JadwalKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')])),
                ('jam_masuk', models.TimeField(help_text='Jam masuk resmi, contoh: 07:00')),
                ('jam_pulang', models.TimeField(help_text='Jam pulang resmi, contoh: 17:15')),
                ('is_active', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_kerja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jadwal Kerja',
                'verbose_name_plural': 'Jadwal Kerja',
                'ordering': ['supervisor', 'hari'],
                'unique_together': {('supervisor', 'hari')},
            },
        ),
        migrations.CreateModel(
            name='KeteranganAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('terlambat', 'Terlambat Masuk'), ('pulang_cepat', 'Pulang Lebih Awal'), ('luar_jadwal', 'Di Luar Jadwal Kerja')], max_length=20)),
                ('alasan', models.TextField(help_text='Alasan wajib diisi oleh staff saat scan.')),
                ('selisih_menit', models.IntegerField(default=0, help_text='Selisih menit terhadap jadwal resmi.')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('catatan_supervisor', models.TextField(blank=True)),
                ('direview_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('absensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keterangan_set', to='outsourcing.absensi')),
                ('direview_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keterangan_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keterangan Absensi',
                'verbose_name_plural': 'Keterangan Absensi',
                'ordering': ['-dibuat_pada'],
                'unique_together': {('absensi', 'tipe')},
            },
        ),
    ]
